#!/bin/bash

# Define the backup directory
backup_dir="~/backed_up"

# Check if the backup directory exists, if not, create it
if [ ! -d "$backup_dir" ]; then
    mkdir "$backup_dir"
fi

# Read the file line by line
while IFS= read -r line
do
  # Use eval to force tilde expansion
  eval line="$line"

  # Check if the file or directory exists
  if [ -e "$line" ]; then
      # Copy the file or directory to the backup directory
      cp -r "$line" "$backup_dir"
  else
    echo "Warning: $line does not exist"
  fi
done < "./tobackup.txt"

# Change to the backup directory
cd "$backup_dir"

# Check if there are any changes
if [ -n "$(git status --porcelain)" ]; then
  # Add changes to the staging area
  git add .

  # Commit changes with a timestamp
  git commit -m "Backup commit $(date)"

  # Push changes to the repository
  git push
else
  echo "No changes to commit"
fi

# Change back to the original directory
cd -

# Remove the backup directory
rm -rf "$backup_dir"
