#!/bin/bash

dir_path="$2"

echo "in nvim script"

# Check the first argument
if [ "$1" == "backup" ]; then
    echo "Backing up nvim"
    rsync -a --delete ~/.config/nvim/ "$dir_path/nvim/"
elif [ "$1" == "recover" ]; then
    echo "Installing neovim"
    sudo snap install nvim --classic

    echo "Recovering nvim"
    rsync -a --delete "$dir_path/nvim/" ~/.config/nvim/
fi

